In [2]:
# Arithmetic operators on arrays apply elementwise. 
# A new array is created and filled with the result.
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(b)

[0 1 2 3]


In [6]:
# prints the individual items in a minus individual of b
c = a - b
print(c)

# squaring the individual elements of b 
print('\nSquares of b')
square = b**2
print(square)

[20 29 38 47]

Squares of b
[0 1 4 9]


In [7]:
# this checks if each element of a is less than 35
print(a < 35)

[ True  True False False]


In [8]:
# Multiplying matrix.. The lines below multiply individual element of A
# with the individual elements of B
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])

print(A * B)

[[2 0]
 [0 4]]


In [18]:
# Matrix product use the @ 
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])
# the @ makes it possible to evaluate the product in a matrix format
print("Matrix Product")
print(A @ B)


Matrix Product

[[5 4]
 [3 4]]


In [19]:
# Another way to multiply the matrix expression
another = A.dot(B)
print(another)

[[5 4]
 [3 4]]


In [23]:
# creating a default random number generator
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
print(b)

# this multiplies a * 3 i.e the same as a = a * 3 
a *= 3
print(a)

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
[[3 3 3]
 [3 3 3]]


In [22]:
# this adds the values of a to the ones of b
b += a
print(b)

[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


In [28]:
# this returns an error since the value of b are not integer values
# a += b
# print(a)

In [29]:
# Generating random numbers in an array with two axes of 3 items
a = rg.random((2,3))
print(a)

[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]


In [30]:
# to find the sum of all elements in the array
a = rg.random((2,3))
sumArray = a.sum()
print(sumArray)

2.412007822394087


In [35]:
# Obtaining the minimum value in the array
a = rg.random((2,3))
minNumber = a.min()
print(f"The minimum item in the array \n{minNumber}")

# Obtaining the maximum value in the array
maxNumber = a.max()
print(f"\nThe maximum item in the array \n{maxNumber}")


The minimum item in the array 
0.11586561247077032

The maximum item in the array 
0.9172977047909027


In [48]:
# By default, these operations apply to the array as though it 
# were a list of numbers, regardless of its shape. However, by
# specifying the axis parameter you can apply an operation along 
# the specified axis of an array

b = np.arange(12).reshape(3, 4)
print(b)

# specifying axis the numbers 0 and 1 specify the direction of the operation
sumAxis = b.sum(axis = 0) # sum of each column vertically in an array
print(f" The sum of each colum is: {sumAxis}")

sumAxis = b.sum(axis = 1) # sum of each row horizontally in an array
print(f" The sum of each row is: {sumAxis}")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 The sum of each colum is: [12 15 18 21]
 The sum of each row is: [ 6 22 38]
The min of each row is: [0 4 8]


In [49]:
# min of each row
minRow = b.min(axis = 1)
print(f"The min of each row is: {minRow}")

# min of each column
minCol = b.min(axis = 0)
print(f"The min of each Col is: {minCol}")

The min of each row is: [0 4 8]
The min of each row is: [0 1 2 3]


In [51]:
# Finding cumulative sum of each row
# the sum keeps increasing as the items are accessed in the array
cumSum = b.cumsum(axis = 1)
print(cumSum)

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
