In [32]:
# When operating and manipulating arrays, their data is sometimes 
# copied into a new array and sometimes not. This is
# often a source of confusion for beginners. There are three cases:
import numpy as np
a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [ 8, 9, 10, 11]])
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
# Senarials where no copy at all
# Simple assignments make no copy of objects or their data.

b = a  # no new object is created. a and b are two names for the same ndarray object
print(b)
print(b is a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
True


In [34]:
# checking their ids to confirm
def checking_both_ids(x):
    print(id(x))

print("ID for an ndarray 'a'")
id(a)

fucntiona = checking_both_ids(a)
print(fucntiona)



ID for an ndarray 'a'
1998489112944
None


In [35]:
# view and shallow copy
# Different array objects can share the same data. The view() method 
# creates a new array object that looks at the same data.
c = a.view()
print(c) # c has the same data as a but is different from a 
print(c is a) # c is a view of data owned by a


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
False


In [36]:
# Since c is just a view of data in a that means using c cant change shape in a
c = c.reshape((2,6)) 
shapeChangeCheck = a.shape
print(shapeChangeCheck)

# but the data in a can be changed rather than the shape
c[0, 4] = 1234
print(a)

(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [42]:
# Slicing an array returns a view of it:
s = a[:, 1:3]
print(s) # s[:] is a view of s



[[ 1  2]
 [ 5  6]
 [ 9 10]]
