### Copying numpy arrays
* using `numpy.copy()`
  * `copy(obj, order='K')`
* Return an array copy of a given object 'obj'
* The possible values are {'C', 'F', 'A', 'K'}.
* This parameter controls the memory layout of the copy.
* 'C' means C-order,
* 'F' means Fortran-order
* 'A' means 'F' if the object 'obj' is Fortran contiguous,'C' otherwise.
* 'K' means match the layout of 'obj' as closely as possible

In [5]:
import numpy as np
x = np.array([[42, 22, 12], [44, 53, 66]], order='F')
y = x.copy()
x[0, 0] = 1001
print("This is the modified array for x: \n",x)
print("\nThis is the copied array: \n", y)

This is the modified array for x: 
 [[1001   22   12]
 [  44   53   66]]

This is the copied array: 
 [[42 22 12]
 [44 53 66]]


#### NDARRAY.COPY
* There is also a ndarray method 'copy' which can be directly applied to an array.
* It is similar to the above function, but the default values for the ordeer arguments are diffferent
* `a.copy(order="C")` Returns a copy of the array

In [9]:
x = np.array([[42, 22, 12],[44, 53, 66]], order="F")
y = x.copy()
x[0, 0] = 1001
print("This is the modified x array:\n ", x)
print("\nThis is the copied ndarray: \n", y)

print(x.flags['C_CONTIGUOUS'])
print(y.flags['C_CONTIGUOUS'])

This is the modified x array:
  [[1001   22   12]
 [  44   53   66]]

This is the copied ndarray: 
 [[42 22 12]
 [44 53 66]]
False
True
