#### EXERCISE 

##### Exercise One
1) Create an arbitrary one dimensional array called "v".

In [4]:
import numpy as np
v = np.array([1, 2, 3, 4, 5, 6, 7])
print(v)

[1 2 3 4 5 6 7]


2) Create a new array which consists of the odd indices of previously created array "v".

In [23]:
odd_elements = np.array([1, 3, 5, 7])
print("This is an array that consits of odd indices of previously created array\n", odd_elements)

v = np.array([1, 2, 3, 4, 5, 6, 7])
odd_elements = v[::2]
print(odd_elements)

This is an array that consits of odd indices of previously created array
 [1 3 5 7]
[1 3 5 7]


3) Create a new array in backwards ordering from "v".

In [11]:
# reverse order
r = v[::-1]
print("Reverse Order\n", r)

Reverse Order
 [1 3 5 7]


4) What will be the output of the following code:

In [25]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4] # The two arrays share the same memory address
b[0] = 200
print(a[1]) # The output is 200 because slices are views in numpy and not copies.

200


5) Create a two dimensional array called "m".

In [26]:
two_dimensional_array = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(two_dimensional_array)

[[1 2 3 4]
 [5 6 7 8]]


6) Create a new array from m, in which the elements of each row are reverse order.

In [32]:
reverse_order = two_dimensional_array[::1, ::-1]
print(reverse_order)

[[4 3 2 1]
 [8 7 6 5]]


7) Another one, where the rows are in reverse order.

In [37]:
reverse_rows = two_dimensional_array[::-1]
print(reverse_rows)

[[5 6 7 8]
 [1 2 3 4]]


8) Create an where the cols are in reverse order

In [38]:
col_reverse = two_dimensional_array[::-1, ::]
print(col_reverse)

[[5 6 7 8]
 [1 2 3 4]]


9) Create an array from m, where columns and rows are in reverse order.

In [39]:
row_col_reverse = two_dimensional_array[::-1, ::-1]
print(row_col_reverse)

[[8 7 6 5]
 [4 3 2 1]]


10)  Cut of the first and last row and the first and last column.

In [45]:
rev = two_dimensional_array[1:2,1:2]
print(rev)

[[6]]
