#### IDENTITY ARRAY
* In linear algebra, the identity matrix, or unit matrix, of size n is the n × n square matrix with ones on the main diagonal and zeros elsewhere.
* There are two ways in Numpy to create identity arrays:
    * identity
    * eye
   

#### THE IDENTITY FUNCTION
* We can create identity arrays with the function identity:
* `identity(n, dtype=None)`
* n defines the number of rows and cols of the output. i.e 'n' x 'n'
* dtype optional argument, defining the data-type of the output. The default is 'float'


In [3]:
import numpy as np
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.identity(4, dtype=int) # same as np.identity(4, int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#### THE EYE FUNCTION
* Another way to create identity arrays provides the function eye. This function creates also diagonal arrays consisting solely of ones.
* It returns a 2-D array with ones on the diagonal and zeros elsewhere.
* `eye(N, M=None, k=0, dtype=float)`
* N :- An optional interger number defining the rows of the output array
* M An optional integer for setting the number of columns in the output. If it is None, it defaults to 'N'
* Defining the position of the diagonal. The default is 0. 0 refers to the main diagonal. A positive value refers to an upper diagonal, and a negative value to a lover diagonal.
* Eye returns an ndarray of shape(N, M). All elements of this array are equal to zero, except for the 'k'th diagonal, whose values are equal to one.

In [16]:
x = np.eye(5, 8, k=2, dtype=int) # 5 rep rows, 8 rep cols, k rep the diag to filled with 1s
print("This is an ndarray with 5 rows and 8 cols and the kth diagonal at index 2\n", x)

y = np.eye(3, 6, k=3, dtype=int)
print("\nThis is an ndarray with 3 rows and 6 cols and the kth diagonal at index 3\n", y)

k = np.eye(5, 8, k=-1, dtype=int)
print("\nThis is an ndarray with 5 rows and 8 cols and the kth diagonal at index -1\n", k)


This is an ndarray with 5 rows and 8 cols and the kth diagonal at index 2
 [[0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]]

This is an ndarray with 3 rows and 6 cols and the kth diagonal at index 3
 [[0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

This is an ndarray with 5 rows and 8 cols and the kth diagonal at index -1
 [[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]
