In [2]:
# One-dimensional arrays can be indexed, sliced and iterated over,
# much like lists and other Python sequences.
import numpy as np

a = np.arange(10) ** 3
print(a)

# slicing the above array
slyc = a[2:5] # remember the last index (5) item is not include 
print(slyc)

# reversing the array
reverse = a[::-1]
print(reverse)

# iterating through the array
for i in a:
    print(i ** (1/3))


[  0   1   8  27  64 125 216 343 512 729]
[ 8 27 64]
[729 512 343 216 125  64  27   8   1   0]
0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [3]:
# Multidimensional arrays can have one index per axis. 
# These indices are given in a tuple separated by commas:

def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype = int)
print(b)

itemIndex = b[1,3] # items at index 1 and 3
print(itemIndex)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
13


In [4]:
# Slicing certain axis or rows
print("\nthis returns the second item in each row of b")
sliceRow = b[0:5, 1] # this returns the second item in each row of b
print(sliceRow)

print("\nreturns all items in the second and third row of b")
# Slicing Colums
sliceCol = b[1:3, :] # returns all items in the second and third row of b
print(sliceCol)


print("\nThe last element or row in b")
last = b[-1]
print(last)


this returns the second item in each row of b
[ 1 11 21 31 41]

returns all items in the second and third row of b
[[10 11 12 13]
 [20 21 22 23]]

The last element or row in b
[40 41 42 43]


In [5]:
# Iterating the multidimensional arrays
for row in b:
    print(row)
    

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [11]:
X = np.arange(28).reshape(4,7)
print('The Original Array\n',X)

print("\nThe Sliced Array\n", X[::2,::3])

print("\nThe Sliced Array\n", X[::2])

The Original Array
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]

The Sliced Array
 [[ 0  3  6]
 [14 17 20]]

The Sliced Array
 [[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]]


In [12]:
print("\nThe Sliced Array Printing teh 1st, 3rd and last cols\n", X[::,::3])


The Sliced Array Printing teh 1st, 3rd and last cols
 [[ 0  3  6]
 [ 7 10 13]
 [14 17 20]
 [21 24 27]]
