# The normal python array list 

In [4]:
a = [1,2,3,4,5]
b = [10, 11,12,13,14]


In [5]:
a + b

[1, 2, 3, 4, 5, 10, 11, 12, 13, 14]

In [6]:
result = []
for first, second in zip(a, b):
    result.append(first + second)

result

[11, 13, 15, 17, 19]

# The tutorial of numpy

In [8]:
import numpy as np

In [9]:
a = np.array([1, 2, 3, 4])
type(a)

numpy.ndarray

In [11]:
a.dtype

dtype('int32')

In [12]:
f = np.array([1.2, 2.3, 4.5, 5.6])
f.dtype

dtype('float64')

In [13]:
# assigning an array 
a[0] = 10

In [14]:
a

array([10,  2,  3,  4])

In [16]:
# the number of dimensions
a.ndim

1

In [18]:
# Size of the array
a.shape

(4,)

In [19]:
# the total number of elements in the array
a.size

4

In [20]:
a

array([10,  2,  3,  4])

In [21]:
b

[10, 11, 12, 13, 14]

In [25]:
a + f

array([11.2,  4.3,  7.5,  9.6])

In [26]:
# Adding elements of different arrays
a + f

array([11.2,  4.3,  7.5,  9.6])

In [27]:
# Multiplying  arrays
f ** a

array([  6.19173642,   5.29      ,  91.125     , 983.4496    ])

# Universal functions (ufuncs)

In [28]:
np.sin(a)

array([-0.54402111,  0.90929743,  0.14112001, -0.7568025 ])

 # MultiDimensional Arrays

In [30]:
a = np.array([[0, 1,2,3,4], [10, 11,12,13,14]])

In [31]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [33]:
a.shape

(2, 5)

In [34]:
a.size

10

# Get or set the elements

In [37]:
# Getting the elements
a[1, 3]

13

In [38]:
# Setting the elements to a specific place
a[1, 3] = -1

In [39]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, -1, 14]])

In [40]:
a[1]

array([10, 11, 12, -1, 14])

# Getting the dimensions of the array

In [36]:
a.ndim

2

## Numpy indexing and slicing

array_name[lower: upper: steps to stride]

In [43]:
a = [10, 11, 12, -1, 14]

In [44]:
a

[10, 11, 12, -1, 14]

In [45]:
a[1:3]

[11, 12]

# Negative indices work
-1 is always the last element of the sequence

In [47]:
a[1:-2] # This returns the second element and the third last element

[11, 12]

In [48]:
a[-4:3]

[11, 12]

# Omitting indices
omitted boundaries are assumed to be te beginning or end of the list

In [49]:
a[:3]

[10, 11, 12]

In [50]:
# grab the last two elements
a[-2:]

[-1, 14]

# specifying some columns while eliminating evry other element

In [52]:
# Go from the begining to the endt but just picking every other element
a[::2]

[10, 12, 14]

# Array Slicing
Slicing and indezing at the same time

In [55]:
# Go to the first row and pick the second and the 3rd element
a = a = np.array([[0, 1,2,3,4], [10, 11,12,13,14]])
a[0, 1:3]

array([1, 2])

In [57]:
a[1:, 4:]

array([[14]])

In [58]:
# Returns the specific column from all rows
a[:, 2]

array([ 2, 12])

# Strides
Utilizing strides to access values in the array

In [61]:
# This returns the first row with the strides of two and all columns
# with The steps of two

a[1::2, ::2]

array([[10, 12, 14]])

In [62]:
# Creating an array using arange and reshape
a = np.arange(25).reshape(5, 5)

In [63]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
# Returning only the two columns
a[:, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [66]:
# Retruning the last row
a[4:, :]

array([[20, 21, 22, 23, 24]])

In [68]:
# returning the second and forth row with a step of 2 and the first 
# and third column with steps of two 
a[1::2, :3:2]

array([[ 5,  7],
       [15, 17]])