In [22]:
import numpy as np

# creating random numbers between 0 and 1
rg = np.random

# This mutliplies the value by 10 then returns the floor(round off to the nearest left)
a = np.floor(10 * rg.random((3, 4)))
print(f"\nThis mutliplies the value by 10 then returns the floor(round off to the nearest left)\n{a}")


# to get the shape of the above
shape = a.shape
print(f"\nHere is the shape of the above:\n{shape}")


This mutliplies the value by 10 then returns the floor(round off to the nearest left)
[[8. 5. 8. 5.]
 [3. 8. 2. 6.]
 [3. 7. 1. 7.]]

Here is the shape of the above:
(3, 4)


In [28]:
# using ravel()
raveledArray = a.ravel() # This returns a flattened array (1d array)
print(f"Using ravel: \n{raveledArray}\n")

# Using reshape()
reshape = a.reshape(6, 2) # This returns an array according to the specified arguments
print(f"Using reshape: \n{reshape}")

# Using a.T for returning a transposed array(switching the col and row nums)
transposed = a.T
print(f"\nThis is a transposed Array:\n{transposed}")



Using ravel: 
[8. 5. 8. 5. 3. 8. 2. 6. 3. 7. 1. 7.]

Using reshape: 
[[8. 5.]
 [8. 5.]
 [3. 8.]
 [2. 6.]
 [3. 7.]
 [1. 7.]]

This is a transposed Array:
[[8. 3. 3.]
 [5. 8. 7.]
 [8. 2. 1.]
 [5. 6. 7.]]


In [32]:
# We can also resize the array using resize()
print(a)

resize = a.resize((2, 6)) # we can not return the variable resize but we just 
# call the array a
print(f"\nThe resized array: \n{a}")

# If a dimension is given as -1 in a reshaping operation, the other dimensions
# are automatically calculated:
ara = a.reshape(3, -1)
print(ara)


[[8. 5. 8. 5. 3. 8.]
 [2. 6. 3. 7. 1. 7.]]

The resized array: 
[[8. 5. 8. 5. 3. 8.]
 [2. 6. 3. 7. 1. 7.]]
[[8. 5. 8. 5.]
 [3. 8. 2. 6.]
 [3. 7. 1. 7.]]


In [42]:
# Stacking together different arrays
a = np.floor(10* rg.random((2, 2)))
print(a)

b = np.floor(10 * rg.random((2, 2)))
print(b)

# using vstack() to vertically stack two arrays together
vstack = np.vstack((a, b))
print(f"\nThis creates a single array that vertically stacks array a onto b\n{vstack}")

# using vstack() to horizontally stack two arrays together
vstack = np.hstack((a, b))
print(f"\nThis creates a single array that horizontally stacks array a onto b\n{vstack}")

[[9. 9.]
 [5. 8.]]
[[1. 3.]
 [3. 9.]]

This creates a single array that vertically stacks array a onto b
[[9. 9.]
 [5. 8.]
 [1. 3.]
 [3. 9.]]

This creates a single array that horizontally stacks array a onto b
[[9. 9. 1. 3.]
 [5. 8. 3. 9.]]


In [43]:
# using column_stack to stack 2d arrays only
stuckArray = np.column_stack((a, b))  # with 2d arrays
print(stuckArray)


[[9. 9. 1. 3.]
 [5. 8. 3. 9.]]


In [49]:
# Difference between column_stack() and hstack()
a = np.array([4, 2])
b = np.array([3, 8])

colStack = np.column_stack((a, b))
print(f"This is a result from column Stack:\n {colStack}\n")

hstack = np.hstack((a, b))
print(f"This is a result from horizontal Stack:\n {hstack}")

This is a result from column Stack:
 [[4 3]
 [2 8]]

This is a result from horizontal Stack:
 [4 2 3 8]
