In [2]:
import numpy as np

# creating random numbers between 0 and 1
rg = np.random

# This mutliplies the value by 10 then returns the floor(round off to the nearest left)
a = np.floor(10 * rg.random((3, 4)))
print(f"\nThis mutliplies the value by 10 then returns the floor(round off to the nearest left)\n{a}")


# to get the shape of the above
shape = a.shape
print(f"\nHere is the shape of the above:\n{shape}")


This mutliplies the value by 10 then returns the floor(round off to the nearest left)
[[4. 9. 5. 2.]
 [7. 1. 4. 5.]
 [2. 4. 9. 7.]]

Here is the shape of the above:
(3, 4)


In [3]:
# using ravel()
raveledArray = a.ravel() # This returns a flattened array (1d array)
print(f"Using ravel: \n{raveledArray}\n")

# Using reshape()
reshape = a.reshape(6, 2) # This returns an array according to the specified arguments
print(f"Using reshape: \n{reshape}")

# Using a.T for returning a transposed array(switching the col and row nums)
transposed = a.T
print(f"\nThis is a transposed Array:\n{transposed}")



Using ravel: 
[4. 9. 5. 2. 7. 1. 4. 5. 2. 4. 9. 7.]

Using reshape: 
[[4. 9.]
 [5. 2.]
 [7. 1.]
 [4. 5.]
 [2. 4.]
 [9. 7.]]

This is a transposed Array:
[[4. 7. 2.]
 [9. 1. 4.]
 [5. 4. 9.]
 [2. 5. 7.]]


In [4]:
# We can also resize the array using resize()
print(a)

resize = a.resize((2, 6)) # we can not return the variable resize but we just 
# call the array a
print(f"\nThe resized array: \n{a}")

# If a dimension is given as -1 in a reshaping operation, the other dimensions
# are automatically calculated:
ara = a.reshape(3, -1)
print(ara)


[[4. 9. 5. 2.]
 [7. 1. 4. 5.]
 [2. 4. 9. 7.]]

The resized array: 
[[4. 9. 5. 2. 7. 1.]
 [4. 5. 2. 4. 9. 7.]]
[[4. 9. 5. 2.]
 [7. 1. 4. 5.]
 [2. 4. 9. 7.]]


In [5]:
# Stacking together different arrays
a = np.floor(10* rg.random((2, 2)))
print(a)

b = np.floor(10 * rg.random((2, 2)))
print(b)

# using vstack() to vertically stack two arrays together
vstack = np.vstack((a, b))
print(f"\nThis creates a single array that vertically stacks array a onto b\n{vstack}")

# using vstack() to horizontally stack two arrays together
vstack = np.hstack((a, b))
print(f"\nThis creates a single array that horizontally stacks array a onto b\n{vstack}")

[[3. 9.]
 [9. 7.]]
[[5. 7.]
 [3. 3.]]

This creates a single array that vertically stacks array a onto b
[[3. 9.]
 [9. 7.]
 [5. 7.]
 [3. 3.]]

This creates a single array that horizontally stacks array a onto b
[[3. 9. 5. 7.]
 [9. 7. 3. 3.]]


In [6]:
# using column_stack to stack 2d arrays only
stuckArray = np.column_stack((a, b))  # with 2d arrays
print(stuckArray)


[[3. 9. 5. 7.]
 [9. 7. 3. 3.]]


In [7]:
# Difference between column_stack() and hstack() on 1d arrays
a = np.array([4, 2])
b = np.array([3, 8])

colStack = np.column_stack((a, b))
print(f"This is a result from column Stack:\n {colStack}\n")

hstack = np.hstack((a, b))
print(f"This is a result from horizontal Stack:\n {hstack}")

This is a result from column Stack:
 [[4 3]
 [2 8]]

This is a result from horizontal Stack:
 [4 2 3 8]


In [10]:
#row_stack() is the same as vstack() but column_stack() is not the same as hstack()
print(np.column_stack is np.hstack)
print(np.row_stack is np.vstack)

False
True
