In [6]:
import numpy as np
arr1 = np.array([[2,4],[3,5]])
arr2 = np.array([[1,2],[3,4]])

print(arr1)
print(arr2)

[[2 4]
 [3 5]]
[[1 2]
 [3 4]]


In [9]:
# operations on the above arrays
arr = arr1 + arr2
print(arr)

# square
arr = arr1**2
print(arr)

# matrix product
matrix = arr1.dot(arr2)
print(matrix)

[[3 6]
 [6 9]]
[[ 4 16]
 [ 9 25]]
[[14 20]
 [18 26]]


In [13]:
# random genetator
rand = np.random.random(12).reshape(2,6)
print(rand)

[[0.871876   0.97991772 0.11770107 0.01669793 0.55707964 0.82394278]
 [0.1193696  0.13072656 0.0252039  0.06293855 0.92590799 0.64114564]]


In [16]:
# USING ONES
ones = np.ones(6).reshape(2,3)
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# min(), max(), sum(), cumsum()
arr1 = np.array([[2,4],[3,5]])
arr2 = np.array([[1,2],[3,4]])

minItem = arr1.min()
print(minItem)

minRowItem = arr1.min(axis = 0)
print(minRowItem)

minColItem = arr1.min(axis = 1)
print(minColItem)

2
[2 4]
[2 3]


In [30]:
# using sum() and cumsum()

# sum of all items in the array
arr = arr2.sum()
print(arr)

# sum of all items in each row
sumRowItems = arr2.sum(axis = 1)
print(sumRowItems)

# sum of all items in each col
sumColItems = arr2.sum(axis = 0)
print(sumColItems)

# cumsum()
cumSum = arr1.cumsum()
print(cumSum)

# Cumulating the sum of colums
cumColSum = arr1.cumsum(axis = 0)
print(cumColSum)

# Cumulating the sum of rows
cumRowSum = arr1.cumsum(axis = 1)
print(cumRowSum)

10
[3 7]
[4 6]
[ 2  6  9 14]
[[2 4]
 [5 9]]
[[2 6]
 [3 8]]


In [36]:
# Indexing, slicing and iterating arrays
ind = np.arange(15)
print(ind)

indtry = np.arange(15).reshape(3, 5)
print(indtry)

# indexing
first = ind[3]
print(first)

# this returns the third list in the array as an item accessed
first = indtry[2]
print(first)

# to returnn an element in the list above we do this
iteminlist = indtry[2, -1] # this returns the last element in the list 
print(iteminlist)




[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
3
[10 11 12 13 14]
14


In [40]:
# slicing the array
arr = np.arange(15).reshape(3, 5)
print(f"The oringinal array: \n{arr}")

sliceArray = arr[1:2]
print(f"\nThe sliced array:\n{sliceArray}")

The oringinal array: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

The sliced array:
[[5 6 7 8 9]]


In [41]:
sliceListItem = arr[1:2, 1:4]
print(sliceListItem)

[[6 7 8]]


In [47]:
# iterating the lists
arr = np.arange(15).reshape(3, 5)
print(f"The oringinal array: \n{arr}")

print(f"\nThe items in the array inclue")
for item in arr:
    print(item)

print(f"\nBreaking futher the array")
for list in arr:
    for item in list:
        print(item)

print(f"\nPrinting items of the first list in the array")
for item in arr[0]:
    print(item)

The oringinal array: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

The items in the array inclue
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]

Breaking futher the array
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14

Printing items of the first list in the array
0
1
2
3
4
