In [6]:
import numpy as np
a = np.array([1, 4, 5, 8], float)
print(a)

print(type(a))

# printing the first two elements of an array
print(a[:2])

# printing  the 4th element
print(a[3])

# changing values of the array
a[0] = 5
print(a)



[1. 4. 5. 8.]
<class 'numpy.ndarray'>
[1. 4.]
8.0
[5. 4. 5. 8.]


In [9]:
# multidimensional arrays
a = np.array([[1,2,3],[4,5,6]], float)
print(a)

# printing the first element in the first array item
print(a[0, 0])

# printing the last item in the second list
print(a[1, 2])

[[1. 2. 3.]
 [4. 5. 6.]]
1.0
6.0


In [21]:
# slicing arrays
a = np.array([[1,2,3],[4,5,6]], float)

# list all elements in the first list
print(f"list all elements in the first list\n{a[1, :]}")

# print the elements at index 2 in the both list
print(f"\nprint the elements at index 2 in the both list:\n{a[:, 2]}")

# print the second last element in the last list
print(f"\nprint the second last element in the last list:\n {a[-1:, -2:]}")

list all elements in the first list
[4. 5. 6.]

print the elements at index 2 in the both list:
[3. 6.]

print the second last element in the last list:
 [[5. 6.]]


In [26]:
print(f"This returns the shape of the array\n{a.shape} 2 rows and 3 cols\n")
print(f"The length of the array:\n{len(a)}")

This returns the shape of the array
(2, 3) 2 rows and 3 cols

The length of the array:
2


In [28]:
# checking whether an element exist in the array 
a = np.array([[1, 2, 3],[4, 5, 6]], float)
print(2 in a) # this confirms the existenc of the element in 

True


In [39]:
# reshaping arrays usign tuples that specify the new dimensions.
a = np.array(range(1, 11), float)
print(a)

# This reshapes the above array to a 2d array with 2 rows and 5 cols
a = a.reshape((5, 2))
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]]


In [42]:
# using copy
a = np.array([1, 2, 3])
b = a # a and b use or access the same memory address storage of the array
c = a.copy() # this creates a seperate file for c

a[0] = 0

print(f"This is array a: \n{a}\n")

print(f"This is array b: \n{b}\n")

print(f"This is array c: \n{c}")


This is array a: 
[0 2 3]

This is array b: 
[0 2 3]

This is array c: 
[1 2 3]


In [47]:
# Creating lists from arrays
print("# Creating lists from arrays")
a_list = a.tolist()
print(a_list)

# or this way 
print("Another way of making a list")
print(list(a))

# Creating lists from arrays
[0, 2, 3]
Another way of making a list
[0, 2, 3]


In [55]:
# convert raw data in an array to a binary string(not in human readable form)
# tostring() function turns an array to string in a non readable form

a = np.array([1,2,3], float)
string = a.tobytes() # tostring() is deprecated use tobytes instead
print(string)

print("")

# fromstring() allows the array to be created from the data later on 
fromstr = np.frombuffer(string)
print(fromstr) # fromstring() is deprecated use frombuffer instead


b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

[1. 2. 3.]


In [61]:
# filling the array with one value

a = np.array([1, 2, 3, 4], int)
print(a)

# Filling the above array with 0s
a.fill(0)

print(a)

[1 2 3 4]
[0 0 0 0]


In [67]:
# Transposing arrays
a = np.array(range(6), float).reshape((2, 3))
print(a)

# tanspose() funtion chages the rows to cols
tansposing = a.transpose() 
print(f"\nTransposed array: \n{tansposing}")

[[0. 1. 2.]
 [3. 4. 5.]]

Transposed array: 
[[0. 3.]
 [1. 4.]
 [2. 5.]]


In [70]:
#  multi-dimensional arrays can be generated with flatten:
flattening = a.flatten()
print(flattening)

[0. 1. 2. 3. 4. 5.]


In [75]:
# Two or more arrays can be concatenated together using the concatenate 
# function with a tuple of the arrays to be joined:

a = np.array([1, 2], int)
b = np.array([3, 4, 5, 6], int)
c = np.arange(7, 12)
d = np.array(range(11, 15))

concat = np.concatenate((a, b, c, d))
print(concat)



[ 1  2  3  4  5  6  7  8  9 10 11 11 12 13 14]
